services:
  prototype_1_next_devContainer:
    env_file:
      - path: .env
        required: false
      - path: ./empty.env
        required: true
    build:
      context: . # Use the Dockerfile in this directory
      dockerfile: Dockerfile
    container_name: prototype_1_next_dev
    volumes:
      - ../../:/workspace
    ports:
      - '3000:3000'
    command: tail -f /dev/null # Keep the container running
