version: '3.9'

services:
  node-react:
    container_name: prototype_1_next_prod
    image: node:lts-alpine
    working_dir: /app
    ports:
      - '1112:3000'
    volumes:
      - ../..:/app
    command: sh -c "npm install && npm start"
    networks:
      - prod-net

networks:
  prod-net:
    driver: bridge
